export default function getEditorColors(scheme, term) {
  return {
    "editor.background": scheme.background,
    "editor.foreground": scheme.onBackground,
    "editorLineNumber.foreground": scheme.onSurfaceVariant,
    "editorLineNumber.activeForeground": scheme.primary,
    "editorLineNumber.dimmedForeground": `${scheme.outline}80`,
    "editorCursor.background": scheme.surfaceContainer,
    "editorCursor.foreground": scheme.primary,
    "editorMultiCursor.primary.foreground": scheme.primary,
    "editorMultiCursor.primary.background": `${scheme.primaryContainer}33`,
    "editorMultiCursor.secondary.foreground": scheme.secondary,
    "editorMultiCursor.secondary.background": `${scheme.secondaryContainer}33`,
    "editor.placeholder.foreground": `${scheme.onSurfaceVariant}90`,
    "editor.compositionBorder": scheme.primary,

    "editor.selectionBackground": `${scheme.primaryContainer}66`,
    "editor.selectionForeground": scheme.onPrimaryContainer,
    "editor.inactiveSelectionBackground": `${scheme.primaryContainer}40`,
    "editor.selectionHighlightBackground": `${scheme.primaryContainer}33`,
    "editor.selectionHighlightBorder": scheme.primary,

    "editor.wordHighlightBackground": `${scheme.secondaryContainer}40`,
    "editor.wordHighlightBorder": scheme.outlineVariant,
    "editor.wordHighlightStrongBackground": `${scheme.secondaryContainer}66`,
    "editor.wordHighlightStrongBorder": scheme.outline,
    "editor.wordHighlightTextBackground": `${scheme.tertiaryContainer}40`,
    "editor.wordHighlightTextBorder": scheme.tertiary,

    "editor.findMatchBackground": `${scheme.tertiaryContainer}66`,
    "editor.findMatchForeground": scheme.onSurface,
    "editor.findMatchHighlightForeground": `${term.normal.yellow}40`,
    "editor.findMatchHighlightBackground": `${scheme.tertiaryContainer}40`,
    "editor.findRangeHighlightBackground": `${scheme.surfaceVariant}50`,
    "editor.findMatchBorder": scheme.tertiary,
    "editor.findMatchHighlightBorder": scheme.error,
    "editor.findRangeHighlightBorder": `${scheme.outlineVariant}50`,

    "search.resultsInfoForeground": scheme.onSurfaceVariant,

    "searchEditor.findMatchBackground": `${scheme.primary}33`,
    "searchEditor.findMatchBorder": scheme.primary,
    "searchEditor.textInputBorder": scheme.primary,

    "editor.hoverHighlightBackground": `${scheme.secondaryContainer}26`,

    "editor.lineHighlightBackground": `${scheme.surfaceContainer}40`,
    "editor.lineHighlightBorder": scheme.outlineVariant,

    "editorWatermark.foreground": `${scheme.onSurfaceVariant}80`,

    "editorUnicodeHighlight.border": scheme.error,
    "editorUnicodeHighlight.background": scheme.surfaceContainer,

    "editorLink.activeForeground": scheme.primary,

    "editor.rangeHighlightBackground": `${scheme.surfaceContainer}66`,
    "editor.rangeHighlightBorder": scheme.surfaceContainer,

    "editor.symbolHighlightBackground": `${scheme.secondaryContainer}33`,
    "editor.symbolHighlightBorder": scheme.secondary,

    "editorWhitespace.foreground": `${scheme.outline}40`,

    "editorIndentGuide.background1": `${term.normal.blue}1A`,
    "editorIndentGuide.background2": `${term.normal.green}1A`,
    "editorIndentGuide.background3": `${term.normal.magenta}1A`,
    "editorIndentGuide.background4": `${term.normal.yellow}1A`,
    "editorIndentGuide.background5": `${term.normal.cyan}1A`,
    "editorIndentGuide.background6": `${term.bright.blue}1A`,
    "editorIndentGuide.activeBackground1": `${term.normal.blue}33`,
    "editorIndentGuide.activeBackground2": `${term.normal.green}33`,
    "editorIndentGuide.activeBackground3": `${term.normal.magenta}33`,
    "editorIndentGuide.activeBackground4": `${term.normal.yellow}33`,
    "editorIndentGuide.activeBackground5": `${term.normal.cyan}33`,
    "editorIndentGuide.activeBackground6": `${term.bright.blue}33`,

    "editorInlayHint.background": scheme.surfaceContainer,
    "editorInlayHint.foreground": scheme.onSurfaceVariant,
    "editorInlayHint.typeForeground": scheme.onTertiaryContainer,
    "editorInlayHint.typeBackground": scheme.tertiaryContainer,
    "editorInlayHint.parameterForeground": scheme.onSecondaryContainer,
    "editorInlayHint.parameterBackground": scheme.secondaryContainer,

    "editorRuler.foreground": `${scheme.outline}40`,

    "editor.linkedEditingBackground": scheme.surfaceContainer,
    "editorCodeLens.foreground": `${scheme.onSurfaceVariant}90`,
    "editorLightBulb.foreground": scheme.tertiary,
    "editorLightBulbAutoFix.foreground": scheme.secondary,
    "editorLightBulbAi.foreground": scheme.primary,
    "editorBracketMatch.background": `${term.normal.blue}1A`,
    "editorBracketMatch.border": term.normal.blue,
    "editorBracketHighlight.foreground1": term.normal.blue,
    "editorBracketHighlight.foreground2": term.normal.green,
    "editorBracketHighlight.foreground3": term.normal.magenta,
    "editorBracketHighlight.foreground4": term.normal.yellow,
    "editorBracketHighlight.foreground5": term.normal.cyan,
    "editorBracketHighlight.foreground6": term.bright.blue,
    "editorBracketHighlight.unexpectedBracket.foreground": term.normal.red,
    "editorBracketPairGuide.activeBackground1": `${term.normal.blue}33`,
    "editorBracketPairGuide.activeBackground2": `${term.normal.green}33`,
    "editorBracketPairGuide.activeBackground3": `${term.normal.magenta}33`,
    "editorBracketPairGuide.activeBackground4": `${term.normal.yellow}33`,
    "editorBracketPairGuide.activeBackground5": `${term.normal.cyan}33`,
    "editorBracketPairGuide.activeBackground6": `${term.bright.blue}33`,
    "editorBracketPairGuide.background1": `${term.normal.blue}1A`,
    "editorBracketPairGuide.background2": `${term.normal.green}1A`,
    "editorBracketPairGuide.background3": `${term.normal.magenta}1A`,
    "editorBracketPairGuide.background4": `${term.normal.yellow}1A`,
    "editorBracketPairGuide.background5": `${term.normal.cyan}1A`,
    "editorBracketPairGuide.background6": `${term.bright.blue}1A`,
    "editor.foldBackground": `${scheme.tertiaryContainer}26`,
    "editor.foldPlaceholderForeground": scheme.outlineVariant,
    "editorOverviewRuler.background": scheme.surfaceContainer,
    "editorOverviewRuler.border": scheme.outlineVariant,
    "editorOverviewRuler.findMatchForeground": `${scheme.tertiary}B3`,
    "editorOverviewRuler.rangeHighlightForeground": `${scheme.surfaceVariant}80`,
    "editorOverviewRuler.selectionHighlightForeground": `${scheme.primaryContainer}80`,
    "editorOverviewRuler.wordHighlightForeground": `${scheme.outline}66`,
    "editorOverviewRuler.wordHighlightStrongForeground": `${scheme.outline}80`,
    "editorOverviewRuler.wordHighlightTextForeground": `${scheme.outline}99`,
    "editorOverviewRuler.modifiedForeground": scheme.primary,
    "editorOverviewRuler.addedForeground": term.normal.green,
    "editorOverviewRuler.deletedForeground": term.normal.red,
    "editorOverviewRuler.errorForeground": term.normal.red,
    "editorOverviewRuler.warningForeground": term.normal.yellow,
    "editorOverviewRuler.infoForeground": term.normal.blue,
    "editorOverviewRuler.bracketMatchForeground": scheme.primary,
    "editorOverviewRuler.inlineChatInserted": term.normal.green,
    "editorOverviewRuler.inlineChatRemoved": term.normal.red,
    "editorError.foreground": term.normal.red,
    "editorError.border": term.normal.red,
    "editorError.background": `${scheme.errorContainer}33`,
    "editorWarning.foreground": term.normal.yellow,
    "editorWarning.border": term.normal.yellow,
    "editorWarning.background": `${scheme.tertiaryContainer}33`,
    "editorInfo.foreground": term.normal.blue,
    "editorInfo.background": `${scheme.primaryContainer}33`,
    "editorInfo.border": term.normal.blue,
    "editorHint.foreground": term.normal.green,
    "editorHint.border": term.normal.green,
    "problemsErrorIcon.foreground": term.normal.red,
    "problemsWarningIcon.foreground": term.normal.yellow,
    "problemsInfoIcon.foreground": term.normal.blue,
    "editorUnnecessaryCode.border": scheme.outlineVariant,
    "editorUnnecessaryCode.opacity": `${scheme.onSurface}66`,
    "editorGutter.background": scheme.surfaceContainer,
    "editorGutter.modifiedBackground": scheme.primary,
    "editorGutter.addedBackground": term.normal.green,
    "editorGutter.deletedBackground": term.normal.red,
    "editorGutter.commentRangeForeground": `${scheme.primary}66`,
    "editorGutter.commentGlyphForeground": scheme.onSurfaceVariant,
    "editorGutter.commentUnresolvedGlyphForeground": scheme.primary,
    "editorGutter.foldingControlForeground": scheme.onSurface,
    "editorCommentsWidget.resolvedBorder": scheme.outlineVariant,
    "editorCommentsWidget.unresolvedBorder": scheme.primary,
    "editorCommentsWidget.rangeBackground": `${scheme.surfaceContainer}99`,
    "editorCommentsWidget.rangeActiveBackground": scheme.surfaceContainer,
    "editorCommentsWidget.replyInputBackground": scheme.surfaceContainerLowest,

    // Editor Inline Edits (Copilot/AI)
    "inlineEdit.gutterIndicator.primaryBorder": scheme.primary,
    "inlineEdit.gutterIndicator.primaryForeground": scheme.onPrimary,
    "inlineEdit.gutterIndicator.primaryBackground": scheme.primary,
    "inlineEdit.gutterIndicator.secondaryBorder": scheme.secondary,
    "inlineEdit.gutterIndicator.secondaryForeground": scheme.onSecondary,
    "inlineEdit.gutterIndicator.secondaryBackground": scheme.secondary,
    "inlineEdit.gutterIndicator.successfulBorder": scheme.tertiary,
    "inlineEdit.gutterIndicator.successfulForeground": scheme.onTertiary,
    "inlineEdit.gutterIndicator.successfulBackground": scheme.tertiary,
    "inlineEdit.gutterIndicator.background": scheme.surfaceContainer,
    "inlineEdit.originalBackground": `${scheme.errorContainer}26`,
    "inlineEdit.modifiedBackground": `${scheme.secondaryContainer}26`,
    "inlineEdit.originalChangedLineBackground": `${scheme.errorContainer}1A`,
    "inlineEdit.originalChangedTextBackground": `${scheme.errorContainer}33`,
    "inlineEdit.modifiedChangedLineBackground": `${scheme.secondaryContainer}1A`,
    "inlineEdit.modifiedChangedTextBackground": `${scheme.secondaryContainer}33`,
    "inlineEdit.originalBorder": scheme.error,
    "inlineEdit.modifiedBorder": scheme.secondary,
    "inlineEdit.tabWillAcceptModifiedBorder": scheme.primary,
    "inlineEdit.tabWillAcceptOriginalBorder": `${scheme.primary}99`,
  };
}
