export default function getEditorColors(scheme) {
  return {
    "editor.background": scheme.background,
    "editor.foreground": scheme.onBackground,
    "editorLineNumber.foreground": scheme.onSurfaceVariant,
    "editorLineNumber.activeForeground": scheme.primary,
    "editorLineNumber.dimmedForeground": `${scheme.outline}80`,
    "editorCursor.background": scheme.surfaceContainer,
    "editorCursor.foreground": scheme.primary,
    "editorMultiCursor.primary.foreground": scheme.primary,
    "editorMultiCursor.primary.background": `${scheme.primaryContainer}33`,
    "editorMultiCursor.secondary.foreground": scheme.secondary,
    "editorMultiCursor.secondary.background": `${scheme.secondaryContainer}33`,
    "editor.placeholder.foreground": `${scheme.onSurfaceVariant}90`,
    "editor.compositionBorder": scheme.primary,

    "editor.selectionBackground": `${scheme.primaryContainer}66`,
    "editor.selectionForeground": scheme.onPrimaryContainer,
    "editor.inactiveSelectionBackground": `${scheme.primaryContainer}40`,
    "editor.selectionHighlightBackground": `${scheme.primaryContainer}33`,
    "editor.selectionHighlightBorder": scheme.primary,

    "editor.wordHighlightBackground": `${scheme.secondaryContainer}40`,
    "editor.wordHighlightBorder": scheme.outlineVariant,
    "editor.wordHighlightStrongBackground": `${scheme.secondaryContainer}66`,
    "editor.wordHighlightStrongBorder": scheme.outline,
    "editor.wordHighlightTextBackground": `${scheme.tertiaryContainer}40`,
    "editor.wordHighlightTextBorder": scheme.tertiary,

    "editor.findMatchBackground": `${scheme.tertiaryContainer}66`,
    "editor.findMatchForeground": scheme.onSurface,
    "editor.findMatchHighlightForeground": scheme.onTertiaryContainer,
    "editor.findMatchHighlightBackground": `${scheme.tertiaryContainer}40`,
    "editor.findRangeHighlightBackground": `${scheme.surfaceVariant}50`,
    "editor.findMatchBorder": scheme.tertiary,
    "editor.findMatchHighlightBorder": scheme.error,
    "editor.findRangeHighlightBorder": `${scheme.outlineVariant}50`,

    "search.resultsInfoForeground": scheme.onSurfaceVariant,

    "searchEditor.findMatchBackground": `${scheme.primary}33`,
    "searchEditor.findMatchBorder": scheme.primary,
    "searchEditor.textInputBorder": scheme.primary,

    "editor.hoverHighlightBackground": `${scheme.secondaryContainer}26`,

    "editor.lineHighlightBackground": `${scheme.surfaceContainer}40`,
    "editor.lineHighlightBorder": scheme.outlineVariant,

    "editorWatermark.foreground": `${scheme.onSurfaceVariant}80`,

    "editorUnicodeHighlight.border": scheme.error,
    "editorUnicodeHighlight.background": scheme.surfaceContainer,

    "editorLink.activeForeground": scheme.primary,

    "editor.rangeHighlightBackground": `${scheme.surfaceContainer}66`,
    "editor.rangeHighlightBorder": scheme.surfaceContainer,

    "editor.symbolHighlightBackground": `${scheme.secondaryContainer}33`,
    "editor.symbolHighlightBorder": scheme.secondary,

    "editorWhitespace.foreground": `${scheme.outline}40`,

    "editorIndentGuide.background1": `${scheme.outline}26`,
    "editorIndentGuide.background2": `${scheme.outline}1A`,
    "editorIndentGuide.background3": `${scheme.outline}33`,
    "editorIndentGuide.background4": `${scheme.outline}1A`,
    "editorIndentGuide.background5": `${scheme.outline}40`,
    "editorIndentGuide.background6": `${scheme.outline}26`,
    "editorIndentGuide.activeBackground1": `${scheme.primary}99`,
    "editorIndentGuide.activeBackground2": `${scheme.primary}66`,
    "editorIndentGuide.activeBackground3": `${scheme.primary}80`,
    "editorIndentGuide.activeBackground4": `${scheme.primary}66`,
    "editorIndentGuide.activeBackground5": `${scheme.primary}8C`,
    "editorIndentGuide.activeBackground6": `${scheme.primary}99`,

    "editorInlayHint.background": scheme.surfaceContainer,
    "editorInlayHint.foreground": scheme.onSurfaceVariant,
    "editorInlayHint.typeForeground": scheme.onTertiaryContainer,
    "editorInlayHint.typeBackground": scheme.tertiaryContainer,
    "editorInlayHint.parameterForeground": scheme.onSecondaryContainer,
    "editorInlayHint.parameterBackground": scheme.secondaryContainer,

    "editorRuler.foreground": `${scheme.outline}40`,

    "editor.linkedEditingBackground": scheme.surfaceContainer,
    "editorCodeLens.foreground": `${scheme.onSurfaceVariant}90`,
    "editorLightBulb.foreground": scheme.tertiary,
    "editorLightBulbAutoFix.foreground": scheme.secondary,
    "editorLightBulbAi.foreground": scheme.primary,
    "editorBracketMatch.background": `${scheme.primaryContainer}4D`,
    "editorBracketMatch.border": scheme.primary,
    "editorBracketHighlight.foreground1": scheme.primary,
    "editorBracketHighlight.foreground2": scheme.secondary,
    "editorBracketHighlight.foreground3": scheme.tertiary,
    "editorBracketHighlight.foreground4": scheme.error,
    "editorBracketHighlight.foreground5": scheme.primary,
    "editorBracketHighlight.foreground6": scheme.secondary,
    "editorBracketHighlight.unexpectedBracket.foreground": scheme.error,
    "editorBracketPairGuide.activeBackground1": `${scheme.primary}33`,
    "editorBracketPairGuide.activeBackground2": `${scheme.secondary}33`,
    "editorBracketPairGuide.activeBackground3": `${scheme.tertiary}33`,
    "editorBracketPairGuide.activeBackground4": `${scheme.error}33`,
    "editorBracketPairGuide.activeBackground5": `${scheme.primary}33`,
    "editorBracketPairGuide.activeBackground6": `${scheme.secondary}33`,
    "editorBracketPairGuide.background1": `${scheme.primary}1A`,
    "editorBracketPairGuide.background2": `${scheme.secondary}1A`,
    "editorBracketPairGuide.background3": `${scheme.tertiary}1A`,
    "editorBracketPairGuide.background4": `${scheme.error}1A`,
    "editorBracketPairGuide.background5": `${scheme.primary}1A`,
    "editorBracketPairGuide.background6": `${scheme.secondary}1A`,
    "editor.foldBackground": `${scheme.tertiaryContainer}99`,
    "editor.foldPlaceholderForeground": scheme.outlineVariant,
    "editorOverviewRuler.background": scheme.surfaceContainer,
    "editorOverviewRuler.border": scheme.outlineVariant,
    "editorOverviewRuler.findMatchForeground": `${scheme.tertiary}B3`,
    "editorOverviewRuler.rangeHighlightForeground": `${scheme.surfaceVariant}80`,
    "editorOverviewRuler.selectionHighlightForeground": `${scheme.primaryContainer}80`,
    "editorOverviewRuler.wordHighlightForeground": `${scheme.outline}66`,
    "editorOverviewRuler.wordHighlightStrongForeground": `${scheme.outline}80`,
    "editorOverviewRuler.wordHighlightTextForeground": `${scheme.outline}99`,
    "editorOverviewRuler.modifiedForeground": scheme.primary,
    "editorOverviewRuler.addedForeground": scheme.secondary,
    "editorOverviewRuler.deletedForeground": scheme.error,
    "editorOverviewRuler.errorForeground": scheme.error,
    "editorOverviewRuler.warningForeground": scheme.tertiary,
    "editorOverviewRuler.infoForeground": scheme.primary,
    "editorOverviewRuler.bracketMatchForeground": scheme.primary,
    "editorOverviewRuler.inlineChatInserted": scheme.secondary,
    "editorOverviewRuler.inlineChatRemoved": scheme.error,
    "editorError.foreground": scheme.error,
    "editorError.border": scheme.error,
    "editorError.background": `${scheme.errorContainer}33`,
    "editorWarning.foreground": scheme.tertiary,
    "editorWarning.border": scheme.tertiary,
    "editorWarning.background": `${scheme.tertiaryContainer}33`,
    "editorInfo.foreground": scheme.primary,
    "editorInfo.background": `${scheme.primaryContainer}33`,
    "editorInfo.border": scheme.primary,
    "editorHint.foreground": scheme.secondary,
    "editorHint.border": scheme.secondary,
    "problemsErrorIcon.foreground": scheme.error,
    "problemsWarningIcon.foreground": scheme.tertiary,
    "problemsInfoIcon.foreground": scheme.primary,
    "editorUnnecessaryCode.border": scheme.outlineVariant,
    "editorUnnecessaryCode.opacity": `${scheme.onSurface}66`,
    "editorGutter.background": scheme.surfaceContainer,
    "editorGutter.modifiedBackground": scheme.primary,
    "editorGutter.addedBackground": scheme.secondary,
    "editorGutter.deletedBackground": scheme.error,
    "editorGutter.commentRangeForeground": `${scheme.primary}66`,
    "editorGutter.commentGlyphForeground": scheme.onSurfaceVariant,
    "editorGutter.commentUnresolvedGlyphForeground": scheme.primary,
    "editorGutter.foldingControlForeground": scheme.onSurface,
    "editorCommentsWidget.resolvedBorder": scheme.outlineVariant,
    "editorCommentsWidget.unresolvedBorder": scheme.primary,
    "editorCommentsWidget.rangeBackground": `${scheme.surfaceContainer}99`,
    "editorCommentsWidget.rangeActiveBackground": scheme.surfaceContainer,
    "editorCommentsWidget.replyInputBackground": scheme.surfaceContainerLowest,

    // Editor Inline Edits (Copilot/AI)
    "inlineEdit.gutterIndicator.primaryBorder": scheme.primary,
    "inlineEdit.gutterIndicator.primaryForeground": scheme.onPrimary,
    "inlineEdit.gutterIndicator.primaryBackground": scheme.primary,
    "inlineEdit.gutterIndicator.secondaryBorder": scheme.secondary,
    "inlineEdit.gutterIndicator.secondaryForeground": scheme.onSecondary,
    "inlineEdit.gutterIndicator.secondaryBackground": scheme.secondary,
    "inlineEdit.gutterIndicator.successfulBorder": scheme.tertiary,
    "inlineEdit.gutterIndicator.successfulForeground": scheme.onTertiary,
    "inlineEdit.gutterIndicator.successfulBackground": scheme.tertiary,
    "inlineEdit.gutterIndicator.background": scheme.surfaceContainer,
    "inlineEdit.originalBackground": `${scheme.errorContainer}26`,
    "inlineEdit.modifiedBackground": `${scheme.secondaryContainer}26`,
    "inlineEdit.originalChangedLineBackground": `${scheme.errorContainer}1A`,
    "inlineEdit.originalChangedTextBackground": `${scheme.errorContainer}33`,
    "inlineEdit.modifiedChangedLineBackground": `${scheme.secondaryContainer}1A`,
    "inlineEdit.modifiedChangedTextBackground": `${scheme.secondaryContainer}33`,
    "inlineEdit.originalBorder": scheme.error,
    "inlineEdit.modifiedBorder": scheme.secondary,
    "inlineEdit.tabWillAcceptModifiedBorder": scheme.primary,
    "inlineEdit.tabWillAcceptOriginalBorder": `${scheme.primary}99`,
  };
}
