export default function getVersionControl(scheme, term) {
  return {
    // Git colors
    "gitDecoration.addedResourceForeground": term.normal.green,
    "gitDecoration.modifiedResourceForeground": term.normal.blue,
    "gitDecoration.deletedResourceForeground": term.normal.red,
    "gitDecoration.renamedResourceForeground": term.normal.cyan,
    "gitDecoration.stageModifiedResourceForeground": term.normal.blue,
    "gitDecoration.stageDeletedResourceForeground": term.normal.red,
    "gitDecoration.untrackedResourceForeground": term.normal.green,
    "gitDecoration.ignoredResourceForeground": scheme.onSurfaceVariant,
    "gitDecoration.conflictingResourceForeground": term.normal.yellow,
    "gitDecoration.submoduleResourceForeground": term.normal.magenta,
    "git.blame.editorDecorationForeground": scheme.onSurfaceVariant,

    // Merge conflicts colors
    "merge.currentHeaderBackground": `${scheme.primary}33`,
    "merge.currentContentBackground": `${scheme.primary}1A`,
    "merge.incomingHeaderBackground": `${scheme.secondary}33`,
    "merge.incomingContentBackground": `${scheme.secondary}1A`,
    "merge.border": scheme.outlineVariant,
    "merge.commonContentBackground": `${scheme.surfaceContainer}80`,
    "merge.commonHeaderBackground": `${scheme.surfaceContainer}B3`,
    "editorOverviewRuler.currentContentForeground": scheme.primary,
    "editorOverviewRuler.incomingContentForeground": scheme.secondary,
    "editorOverviewRuler.commonContentForeground": scheme.outline,
    "editorOverviewRuler.commentForeground": scheme.primary,
    "editorOverviewRuler.commentUnresolvedForeground": scheme.secondary,
    "mergeEditor.change.background": `${scheme.primary}1A`,
    "mergeEditor.change.word.background": `${scheme.primary}33`,
    "mergeEditor.conflict.unhandledUnfocused.border": scheme.error,
    "mergeEditor.conflict.unhandledFocused.border": scheme.error,
    "mergeEditor.conflict.handledUnfocused.border": scheme.primary,
    "mergeEditor.conflict.handledFocused.border": scheme.primary,
    "mergeEditor.conflict.handled.minimapOverViewRuler": scheme.primary,
    "mergeEditor.conflict.unhandled.minimapOverViewRuler": scheme.error,
    "mergeEditor.conflictingLines.background": `${scheme.surfaceContainer}4D`,
    "mergeEditor.changeBase.background": `${scheme.surfaceContainer}33`,
    "mergeEditor.changeBase.word.background": `${scheme.surfaceContainer}66`,
    "mergeEditor.conflict.input1.background": `${scheme.primary}1A`,
    "mergeEditor.conflict.input2.background": `${scheme.secondary}1A`,

    // Peek view colors
    "peekView.border": scheme.outlineVariant,
    "peekViewEditor.background": scheme.surfaceContainerLowest,
    "peekViewEditorGutter.background": scheme.surfaceContainer,
    "peekViewEditor.matchHighlightBackground": `${scheme.tertiaryContainer}66`,
    "peekViewEditor.matchHighlightBorder": scheme.tertiary,
    "peekViewResult.background": scheme.surfaceContainer,
    "peekViewResult.fileForeground": scheme.onSurface,
    "peekViewResult.lineForeground": scheme.onSurfaceVariant,
    "peekViewResult.matchHighlightBackground": `${scheme.error}33`,
    "peekViewResult.selectionBackground": scheme.surfaceContainerHigh,
    "peekViewResult.selectionForeground": scheme.onSurface,
    "peekViewTitle.background": scheme.surfaceContainerHigh,
    "peekViewTitleDescription.foreground": scheme.onSurfaceVariant,
    "peekViewTitleLabel.foreground": scheme.onSurface,

    // Source Control Graph colors
    "scmGraph.historyItemHoverLabelForeground": scheme.onSurface,
    "scmGraph.foreground1": scheme.primary,
    "scmGraph.foreground2": scheme.secondary,
    "scmGraph.foreground3": scheme.tertiary,
    "scmGraph.foreground4": scheme.error,
    "scmGraph.foreground5": scheme.onSurfaceVariant,
    "scmGraph.historyItemHoverAdditionsForeground": scheme.secondary,
    "scmGraph.historyItemHoverDeletionsForeground": scheme.error,
    "scmGraph.historyItemRefColor": scheme.primary,
    "scmGraph.historyItemRemoteRefColor": scheme.secondary,
    "scmGraph.historyItemBaseRefColor": scheme.tertiary,
    "scmGraph.historyItemHoverDefaultLabelForeground": scheme.onSurfaceVariant,
    "scmGraph.historyItemHoverDefaultLabelBackground": scheme.surfaceContainer,
  };
}
