export default function getEditorColors(scheme) {
  return {
    "editor.background": scheme.background,
    "editor.foreground": scheme.onBackground,
    "editorLineNumber.foreground": scheme.outline,
    "editorLineNumber.activeForeground": scheme.primary,
    // "editorLineNumber.dimmedForeground": `${scheme.outline}60`,
    "editorCursor.background": scheme.surfaceContainer,
    "editorCursor.foreground": scheme.primary,
    // "editorMultiCursor.primary.foreground": scheme.primary,
    // "editorMultiCursor.primary.background": `${scheme.primary}20`,
    // "editorMultiCursor.secondary.foreground": scheme.secondary,
    // "editorMultiCursor.secondary.background": `${scheme.secondary}20`,
    // "editor.placeholder.foreground": `${scheme.onSurfaceVariant}80`,
    // "editor.compositionBorder": scheme.primary,

    "editor.selectionBackground": `${scheme.primaryContainer}40`,
    // "editor.selectionForeground": scheme.onPrimaryContainer,
    "editor.inactiveSelectionBackground": `${scheme.secondaryContainer}40`,
    "editor.selectionHighlightBackground": `${scheme.primaryContainer}20`,
    "editor.selectionHighlightBorder": scheme.primary,

    "editor.wordHighlightBackground": `${scheme.secondaryContainer}30`,
    "editor.wordHighlightBorder": scheme.outlineVariant,
    "editor.wordHighlightStrongBackground": `${scheme.secondaryContainer}50`,
    "editor.wordHighlightStrongBorder": scheme.outline,
    // "editor.wordHighlightTextBackground": `${scheme.tertiaryContainer}40`,
    // "editor.wordHighlightTextBorder": scheme.tertiary,

    "editor.findMatchBackground": `${scheme.tertiary}60`,
    "editor.findMatchForeground": scheme.onTertiary,
    // "editor.findMatchHighlightForeground": scheme.onTertiaryContainer,
    "editor.findMatchHighlightBackground": `${scheme.tertiary}30`,
    "editor.findRangeHighlightBackground": `${scheme.surfaceVariant}50`,
    "editor.findMatchBorder": scheme.tertiary,
    "editor.findMatchHighlightBorder": scheme.error,
    "editor.findRangeHighlightBorder": `${scheme.outlineVariant}50`,

    "search.resultsInfoForeground": scheme.onSurfaceVariant,

    "searchEditor.findMatchBackground": `${scheme.primary}20`,
    "searchEditor.findMatchBorder": scheme.primary,
    "searchEditor.textInputBorder": scheme.primary,

    "editor.hoverHighlightBackground": `${scheme.secondaryContainer}50`,

    "editor.lineHighlightBackground": `${scheme.surfaceVariant}20`,
    "editor.lineHighlightBorder": scheme.outlineVariant,

    "editorWatermark.foreground": `${scheme.onSurfaceVariant}60`,

    "editorUnicodeHighlight.border": scheme.error,
    "editorUnicodeHighlight.background": scheme.surfaceContainer,

    "editorLink.activeForeground": scheme.primary,

    "editor.rangeHighlightBackground": `${scheme.surfaceContainer}50`,
    "editor.rangeHighlightBorder": scheme.surfaceContainer,

    // "editor.symbolHighlightBackground": `${scheme.secondaryContainer}25`,
    // "editor.symbolHighlightBorder": scheme.secondary,

    "editorWhitespace.foreground": `${scheme.outline}40`,

    "editorIndentGuide.background1": `${scheme.outline}20`,
    // "editorIndentGuide.background2": `${scheme.outline}15`,
    // "editorIndentGuide.background3": `${scheme.outline}25`,
    // "editorIndentGuide.background4": `${scheme.outline}15`,
    // "editorIndentGuide.background5": `${scheme.outline}30`,
    // "editorIndentGuide.background6": `${scheme.outline}20`,
    "editorIndentGuide.activeBackground1": `${scheme.primary}60`,
    // "editorIndentGuide.activeBackground2": `${scheme.primary}40`,
    // "editorIndentGuide.activeBackground3": `${scheme.primary}50`,
    // "editorIndentGuide.activeBackground4": `${scheme.primary}40`,
    // "editorIndentGuide.activeBackground5": `${scheme.primary}55`,
    // "editorIndentGuide.activeBackground6": `${scheme.primary}60`,

    "editorInlayHint.background": scheme.surfaceContainer,
    "editorInlayHint.foreground": scheme.onSurfaceVariant,
    // "editorInlayHint.typeForeground": scheme.onTertiaryContainer,
    // "editorInlayHint.typeBackground": scheme.tertiaryContainer,
    // "editorInlayHint.parameterForeground": scheme.onSecondaryContainer,
    // "editorInlayHint.parameterBackground": scheme.secondaryContainer,

    "editorRuler.foreground": `${scheme.outline}30`,

    "editor.linkedEditingBackground": scheme.surfaceContainer,
    "editorCodeLens.foreground": scheme.onSurfaceVariant,
    "editorLightBulb.foreground": scheme.tertiary,
    "editorLightBulbAutoFix.foreground": scheme.secondary,
    "editorLightBulbAi.foreground": scheme.primary,
    "editorBracketMatch.background": `${scheme.primary}30`,
    "editorBracketMatch.border": scheme.primary,
    // "editorBracketHighlight.foreground1": scheme.primary,
    // "editorBracketHighlight.foreground2": scheme.secondary,
    // "editorBracketHighlight.foreground3": scheme.tertiary,
    // "editorBracketHighlight.foreground4": scheme.error,
    // "editorBracketHighlight.foreground5": scheme.primary,
    // "editorBracketHighlight.foreground6": scheme.secondary,
    // "editorBracketHighlight.unexpectedBracket.foreground": scheme.error,
    // "editorBracketPairGuide.activeBackground1": `${scheme.primary}20`,
    // "editorBracketPairGuide.activeBackground2": `${scheme.secondary}20`,
    // "editorBracketPairGuide.activeBackground3": `${scheme.tertiary}20`,
    // "editorBracketPairGuide.activeBackground4": `${scheme.error}20`,
    // "editorBracketPairGuide.activeBackground5": `${scheme.primary}20`,
    // "editorBracketPairGuide.activeBackground6": `${scheme.secondary}20`,
    // "editorBracketPairGuide.background1": `${scheme.primary}10`,
    // "editorBracketPairGuide.background2": `${scheme.secondary}10`,
    // "editorBracketPairGuide.background3": `${scheme.tertiary}10`,
    // "editorBracketPairGuide.background4": `${scheme.error}10`,
    // "editorBracketPairGuide.background5": `${scheme.primary}10`,
    // "editorBracketPairGuide.background6": `${scheme.secondary}10`,
    "editor.foldBackground": `${scheme.primaryContainer}50`,
    "editor.foldPlaceholderForeground": scheme.outlineVariant,
    "editorOverviewRuler.background": scheme.surfaceContainer,
    "editorOverviewRuler.border": scheme.outlineVariant,
    "editorOverviewRuler.findMatchForeground": `${scheme.tertiary}70`,
    "editorOverviewRuler.rangeHighlightForeground": `${scheme.surfaceVariant}50`,
    "editorOverviewRuler.selectionHighlightForeground": `${scheme.primaryContainer}50`,
    "editorOverviewRuler.wordHighlightForeground": `${scheme.outline}40`,
    "editorOverviewRuler.wordHighlightStrongForeground": `${scheme.outline}50`,
    "editorOverviewRuler.wordHighlightTextForeground": `${scheme.outline}60`,
    "editorOverviewRuler.modifiedForeground": scheme.primary,
    "editorOverviewRuler.addedForeground": scheme.secondary,
    "editorOverviewRuler.deletedForeground": scheme.error,
    "editorOverviewRuler.errorForeground": scheme.error,
    "editorOverviewRuler.warningForeground": scheme.tertiary,
    "editorOverviewRuler.infoForeground": scheme.primary,
    "editorOverviewRuler.bracketMatchForeground": scheme.primary,
    "editorOverviewRuler.inlineChatInserted": scheme.secondary,
    "editorOverviewRuler.inlineChatRemoved": scheme.error,
    // "editorError.foreground": scheme.error,
    // "editorError.border": scheme.error,
    // "editorError.background": `${scheme.error}20`,
    // "editorWarning.foreground": scheme.tertiary,
    // "editorWarning.border": scheme.tertiary,
    // "editorWarning.background": `${scheme.tertiary}20`,
    // "editorInfo.foreground": scheme.primary,
    // "editorInfo.background": `${scheme.primary}20`,
    // "editorInfo.border": scheme.primary,
    "editorHint.foreground": scheme.secondary,
    "editorHint.border": scheme.secondary,
    "problemsErrorIcon.foreground": scheme.error,
    "problemsWarningIcon.foreground": scheme.tertiary,
    "problemsInfoIcon.foreground": scheme.primary,
    // "editorUnnecessaryCode.border": scheme.outlineVariant,
    // "editorUnnecessaryCode.opacity": `${scheme.outline}40`,
    "editorGutter.background": `${scheme.surfaceContainer}40`,
    "editorGutter.modifiedBackground": scheme.primary,
    "editorGutter.addedBackground": scheme.secondary,
    "editorGutter.deletedBackground": scheme.error,
    "editorGutter.commentRangeForeground": `${scheme.primary}40`,
    "editorGutter.commentGlyphForeground": scheme.onSurfaceVariant,
    "editorGutter.commentUnresolvedGlyphForeground": scheme.primary,
    "editorGutter.foldingControlForeground": scheme.onSurface,
    "editorCommentsWidget.resolvedBorder": scheme.outlineVariant,
    "editorCommentsWidget.unresolvedBorder": scheme.primary,
    "editorCommentsWidget.rangeBackground": `${scheme.surfaceContainer}60`,
    "editorCommentsWidget.rangeActiveBackground": scheme.surfaceContainer,
    "editorCommentsWidget.replyInputBackground": scheme.surfaceContainerLowest,
  };
}
