export default function getMetaSettings(scheme) {
  return {
    name: "Meta scopes are used for larger code or markup portions, often containing the complete contents of multiple more specific scope data structures",
    scope: [
      "meta.class",
      "meta.struct",
      "meta.enum",
      "meta.union",
      "meta.trait",
      "meta.interface",
      "meta.impl",
      "meta.type",
      "meta.function",
      "meta.function.parameters",
      "meta.function.return-type",
      "meta.namespace",
      "meta.preprocessor",
      "meta.annotation",
      "meta.annotation.identifier",
      "meta.annotation.parameters",
      "meta.path",
      "meta.function-call",
      "meta.block",
      "meta.braces",
      "meta.group",
      "meta.parens",
      "meta.brackets",
      "meta.generic",
      "meta.tag",
      "meta.paragraph",
    ],
    settings: {
      foreground: scheme.onSurfaceVariant,
      fontStyle: "",
    },
  };
}
